/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_evil_EvilMethodClass */

#ifndef _Included_com_evil_EvilMethodClass
#define _Included_com_evil_EvilMethodClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_evil_EvilMethodClass
 * Method:    evilMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_evil_EvilMethodClass_evilMethod
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
